In [7]:
import numpy as np

In [8]:
n = 5
A = np.random.random((n,n))
A_iter = A.copy()

In [9]:
D1 = np.eye(n) # To scale the rows
D2 = np.eye(n) # To scale the columns

In [10]:
D1.dot(A.dot(D2))

array([[0.53191361, 0.11465924, 0.15092669, 0.18667888, 0.40471929],
       [0.19571462, 0.83360296, 0.18520861, 0.66714433, 0.10853216],
       [0.52411749, 0.97078613, 0.64525454, 0.10887908, 0.51849666],
       [0.1422673 , 0.31541896, 0.64528855, 0.08033692, 0.09451495],
       [0.06082176, 0.64994305, 0.303521  , 0.04096097, 0.69741668]])

In [11]:
n_iterations = 30
for i in range(n_iterations):
    column_sums = A_iter.sum(axis=0)
    row_sums = A_iter.sum(axis=1)
    if (i % 2 )== 0:
        D1 *= np.diag(1.0 / row_sums)
    else:
        D2 *= np.diag(1.0 / column_sums)
    A_iter = D1.dot(A.dot(D2)) 
    print(A_iter.sum(axis=0), A_iter.sum(axis=1))

[0.81673294 1.46985583 1.11304426 0.59520442 1.00516255] [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] [1.1384237  1.1064212  0.93247973 0.93716676 0.88550861]
[0.96282593 1.02692118 1.0457903  0.93531631 1.02914629] [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] [1.01736078 1.02795473 0.99229689 0.98529193 0.97709567]
[0.99505442 1.00340283 1.00915186 0.98507955 1.00731134] [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] [1.0025909  1.00676405 0.99821484 0.99719103 0.99523917]
[0.99931257 1.00054321 1.00183576 0.99656627 1.00174219] [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] [1.0004269  1.00157746 0.99957943 0.99944961 0.99896661]
[0.99989583 1.00009664 1.00038097 0.99921892 1.00040764] [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] [1.00007669 1.00036139 0.99990312 0.99988778 0.99977102]
[0.99998265 1.00001865 1.00008127 0.99982339 1.00009405] [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] [1.00001482 1.00008204 0.99997795 0.99997637 0.99994881]
[0.99999684 1.00000382 1.00001767 0.99996018 1.00002149] [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] [1.00000303 1.0000185

In [12]:
A_normalised = D1.dot(A.dot(D2))
print(A_normalised)

[[0.42161868 0.04688502 0.07944118 0.21190037 0.24015475]
 [0.10962125 0.24086688 0.06888641 0.53511738 0.04550808]
 [0.26238938 0.25071915 0.21451099 0.07805843 0.19432205]
 [0.15475774 0.17700332 0.4661247  0.12514693 0.07696731]
 [0.05161295 0.28452563 0.17103672 0.04977689 0.44304781]]


In [13]:
print(A_normalised.sum(0), A_normalised.sum(1))

[1. 1. 1. 1. 1.] [1. 1. 1. 1. 1.]
